jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build
      run: './gradlew -S -Pskip.signing assemble

        unset GEM_PATH GEM_HOME JRUBY_OPTS

        ./gradlew -S -Pskip.signing check

        '
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - temurin
        java:
        - '11'
        - '17'
        - '21'
        os:
        - ubuntu-latest
        - macos-latest
      max-parallel: 6
  build-windows:
    name: Build on Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Assemble
      run: 'gradlew.bat -i assemble

        '
      shell: cmd
    - continue-on-error: true
      name: Check
      run: 'gradlew.bat -i -S check

        '
      shell: cmd
    - continue-on-error: true
      env:
        java_version: ${{ matrix.java }}
        os_name: ${{ matrix.os }}
      if: always()
      name: Upload asciidoctorj-core reports
      uses: actions/upload-artifact@v3
      with:
        name: asciidoctorj-core-reports-${{ env.os_name }}-${{ env.java_version }}
        path: asciidoctorj-core/build/reports/*
    - continue-on-error: true
      env:
        java_version: ${{ matrix.java }}
        os_name: ${{ matrix.os }}
      if: always()
      name: Upload asciidoctorj-documentation reports
      uses: actions/upload-artifact@v3
      with:
        name: asciidoctorj-documentation-reports-${{ env.os_name }}-${{ env.java_version
          }}
        path: asciidoctorj-documentation/build/reports/*
    strategy:
      fail-fast: false
      matrix:
        distribution:
        - temurin
        java:
        - '11'
        - '17'
        - '21'
        os:
        - windows-latest
      max-parallel: 3
  test-asciidoctor-upstream:
    name: Test Asciidoctor Upstream
    needs:
    - build
    - build-windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Setup Java
      uses: s4u/setup-maven-action@v1.7.0
      with:
        java-distribution: temurin
        java-version: ${{ matrix.java }}
        maven-version: ${{ matrix.maven }}
    - continue-on-error: true
      name: Upstream Build
      run: 'unset GEM_PATH GEM_HOME JRUBY_OPTS

        ./ci/test-asciidoctor-upstream.sh

        '
    - continue-on-error: true
      env:
        java_version: ${{ matrix.java }}
        os_name: ${{ matrix.os }}
      if: always()
      name: Upload asciidoctorj-core reports
      uses: actions/upload-artifact@v3
      with:
        name: asciidoctorj-core-reports-upstream-${{ env.os_name }}-${{ env.java_version
          }}
        path: asciidoctorj-core/build/reports/*
    strategy:
      fail-fast: false
      matrix:
        java:
        - '11'
        - '17'
        - '21'
        maven:
        - 3.9.4
        os:
        - ubuntu-latest
      max-parallel: 2
name: Build Main
on:
  repository_dispatch:
    types: trigger-ga___continuous-integration.yaml
