env:
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSS_SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSS_SONATYPE_USERNAME }}
jobs:
  release:
    environment: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build
      run: 'unset GEM_PATH GEM_HOME JRUBY_OPTS

        ./gradlew --no-daemon clean build

        ./gradlew --no-daemon publishToSonatype closeSonatypeStagingRepository

        '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yaml
