jobs:
  build-upstream:
    name: ${{ github.event.client_payload.message }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build
      run: 'unset GEM_PATH GEM_HOME JRUBY_OPTS

        ./ci/test-asciidoctor-upstream.sh ${{ github.event.client_payload.branch }}

        '
name: Build Upstream
on:
  repository_dispatch:
    types: trigger-ga___upstream-build.yaml
